package com.malaram.reelsdownloader;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;
public class HomeActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.NAVY);setContentView(page());}
 private View page(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,18),Ui.dp(this,22),Ui.dp(this,18),Ui.dp(this,16));root.setBackgroundColor(Ui.NAVY);
 TextView title=Ui.text(this,"ReelMate",27,Color.WHITE);title.setTypeface(null,1);root.addView(title);TextView sub=Ui.text(this,"Instagram media companion",13,Ui.MUTED);root.addView(sub);Ui.space(root,this,24);
 LinearLayout hero=Ui.card(this,Ui.CARD);TextView h=Ui.text(this,"Download a Reel",22,Color.WHITE);h.setTypeface(null,1);hero.addView(h);TextView d=Ui.text(this,"Paste a supported public link and continue.",14,Color.rgb(203,213,225));d.setPadding(0,Ui.dp(this,7),0,Ui.dp(this,16));hero.addView(d);Button open=Ui.button(this,"Open Download Tool",Ui.PURPLE,Color.WHITE);open.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));hero.addView(open,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));root.addView(hero);
 Ui.space(root,this,18);LinearLayout quick=Ui.card(this,Color.WHITE);TextView q=Ui.text(this,"Quick access",18,Ui.NAVY);q.setTypeface(null,1);quick.addView(q);
 add(quick,"Downloads","View download information",DownloadsActivity.class);add(quick,"Help & Guide","Learn how to use ReelMate",HelpActivity.class);add(quick,"Creator Profile","Meet the app creator",ProfileActivity.class);root.addView(quick,new LinearLayout.LayoutParams(-1,0,1f));
 LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);String[] names={"Home","Downloads","Help","Profile"};Class[] cls={HomeActivity.class,DownloadsActivity.class,HelpActivity.class,ProfileActivity.class};for(int i=0;i<4;i++){Button n=Ui.button(this,names[i],i==0?Ui.PURPLE:Ui.CARD,Color.WHITE);final Class c=cls[i];n.setOnClickListener(v->{if(c!=HomeActivity.class)startActivity(new Intent(this,c));});nav.addView(n,new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));}root.addView(nav);return root;}
 private void add(LinearLayout p,String a,String b,Class c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(0,Ui.dp(this,14),0,Ui.dp(this,6));TextView t=Ui.text(this,a,16,Ui.NAVY);t.setTypeface(null,1);TextView d=Ui.text(this,b,12,Color.DKGRAY);x.addView(t);x.addView(d);x.setOnClickListener(v->startActivity(new Intent(this,c)));p.addView(x);}
}