package com.malaram.reelsdownloader;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;
public class HomeActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.NAVY);setContentView(page());}
 private View page(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,20),Ui.dp(this,24),Ui.dp(this,20),Ui.dp(this,16));root.setBackgroundColor(Ui.NAVY);
 LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);TextView brand=Ui.heading(this,"ReelMate");top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button settings=Ui.button(this,"⚙",Ui.CARD,Color.WHITE);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));top.addView(settings,new LinearLayout.LayoutParams(Ui.dp(this,54),Ui.dp(this,48)));root.addView(top);
 TextView sub=Ui.subtitle(this,"Your simple media companion");sub.setPadding(0,Ui.dp(this,4),0,0);root.addView(sub);Ui.space(root,this,28);
 LinearLayout hero=Ui.card(this,Ui.CARD);TextView badge=Ui.text(this,"READY WHEN YOU ARE",11,Color.rgb(196,181,253));hero.addView(badge);TextView h=Ui.text(this,"Download media
in a few taps.",27,Color.WHITE);h.setTypeface(null,1);h.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,8));hero.addView(h);TextView d=Ui.text(this,"Paste a supported public link and let ReelMate handle the rest.",14,Color.rgb(203,213,225));hero.addView(d);Ui.space(hero,this,18);Button open=Ui.button(this,"Open Download Tool  →",Ui.PURPLE,Color.WHITE);open.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));hero.addView(open,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));root.addView(hero);
 Ui.space(root,this,18);LinearLayout info=Ui.card(this,Color.WHITE);TextView it=Ui.text(this,"How it works",18,Ui.NAVY);it.setTypeface(null,1);info.addView(it);TextView steps=Ui.text(this,"1  Copy link     2  Paste link     3  Download",13,Color.rgb(71,85,105));steps.setPadding(0,Ui.dp(this,12),0,0);info.addView(steps);root.addView(info);
 Space flex=new Space(this);root.addView(flex,new LinearLayout.LayoutParams(1,0,1));
 LinearLayout nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);String[] names={"⌂\nHome","↓\nDownloads","?\nHelp","●\nProfile"};Class[] cls={HomeActivity.class,DownloadsActivity.class,HelpActivity.class,ProfileActivity.class};for(int i=0;i<4;i++){Button n=Ui.button(this,names[i],i==0?Ui.PURPLE:Ui.CARD,Color.WHITE);n.setTextSize(10);final Class c=cls[i];n.setOnClickListener(v->{if(c!=HomeActivity.class)startActivity(new Intent(this,c));});nav.addView(n,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));}root.addView(nav);return root;}
}