package com.malaram.reelsdownloader;
import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;
public class HomeActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.NAVY);getWindow().setNavigationBarColor(Ui.NAVY);setContentView(page());}
 private View page(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(Ui.dp(this,20),Ui.dp(this,18),Ui.dp(this,20),Ui.dp(this,12));r.setBackgroundColor(Ui.NAVY);
 LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView logo=Ui.text(this,"RM",17,Color.WHITE);logo.setTypeface(null,1);logo.setGravity(Gravity.CENTER);logo.setBackground(Ui.bg(this,Ui.PURPLE,18));top.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,48),Ui.dp(this,48)));
 TextView brand=Ui.heading(this,"ReelMate");brand.setPadding(Ui.dp(this,12),0,0,0);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));Button set=Ui.button(this,"Settings",Ui.CARD,Color.WHITE);set.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));top.addView(set,new LinearLayout.LayoutParams(Ui.dp(this,92),Ui.dp(this,46)));r.addView(top);
 TextView sub=Ui.subtitle(this,"Save public media you have permission to download");sub.setPadding(Ui.dp(this,60),0,0,0);r.addView(sub);Ui.space(r,this,22);
 TextView hello=Ui.text(this,"Ready when you are.",26,Color.WHITE);hello.setTypeface(null,1);r.addView(hello);TextView intro=Ui.subtitle(this,"Paste a link, preview the available media, and save it in a few simple steps.");intro.setPadding(0,Ui.dp(this,6),0,0);r.addView(intro);Ui.space(r,this,18);
 LinearLayout action=Ui.card(this,Ui.CARD);TextView at=Ui.text(this,"PASTE A PUBLIC LINK",11,Color.rgb(196,181,253));at.setTypeface(null,1);action.addView(at);TextView ah=Ui.text(this,"Start a new download",20,Color.WHITE);ah.setTypeface(null,1);ah.setPadding(0,Ui.dp(this,8),0,Ui.dp(this,5));action.addView(ah);TextView ad=Ui.text(this,"Open the download tool to paste your link.",14,Ui.MUTED);action.addView(ad);Ui.space(action,this,16);Button open=Ui.button(this,"Open Download Tool",Ui.PURPLE,Color.WHITE);open.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));action.addView(open,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));r.addView(action);
 Ui.space(r,this,16);LinearLayout mini=new LinearLayout(this);mini.setOrientation(LinearLayout.HORIZONTAL);LinearLayout a=miniCard("Quick guide","3 simple steps");a.setOnClickListener(v->startActivity(new Intent(this,HelpActivity.class)));LinearLayout d=miniCard("Downloads","Your saved media");d.setOnClickListener(v->startActivity(new Intent(this,DownloadsActivity.class)));mini.addView(a,new LinearLayout.LayoutParams(0,Ui.dp(this,88),1));LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(0,Ui.dp(this,88),1);dp.leftMargin=Ui.dp(this,12);mini.addView(d,dp);r.addView(mini);
 Space flex=new Space(this);r.addView(flex,new LinearLayout.LayoutParams(1,0,1));LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER);String[] names={"Home","Downloads","Help","Profile"};Class[] cls={HomeActivity.class,DownloadsActivity.class,HelpActivity.class,ProfileActivity.class};for(int i=0;i<4;i++){Button n=Ui.button(this,names[i],i==0?Ui.PURPLE:Ui.CARD,Color.WHITE);final Class c=cls[i];n.setOnClickListener(v->{if(c!=HomeActivity.class)startActivity(new Intent(this,c));});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,Ui.dp(this,52),1);if(i>0)p.leftMargin=Ui.dp(this,6);nav.addView(n,p);}r.addView(nav);return r;}
 private LinearLayout miniCard(String t,String s){LinearLayout c=Ui.card(this,Ui.CARD);c.setPadding(Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14),Ui.dp(this,12));TextView a=Ui.text(this,t,15,Color.WHITE);a.setTypeface(null,1);c.addView(a);TextView b=Ui.text(this,s,12,Ui.MUTED);b.setPadding(0,Ui.dp(this,5),0,0);c.addView(b);return c;}
}