package com.malaram.reelsdownloader;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(7,13,28), BAR=Color.rgb(12,17,37), CARD=Color.rgb(23,31,53), CARD2=Color.rgb(29,39,64);
    private static final int TEXT=Color.rgb(248,248,252), MUTED=Color.rgb(158,164,185), PURPLE=Color.rgb(145,78,255), PINK=Color.rgb(201,91,225), GREEN=Color.rgb(54,211,153);
    private LinearLayout body,bottom; private EditText urlBox; private TextView toolStatus,downloadButton; private final ExecutorService executor=Executors.newSingleThreadExecutor();
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BAR);getWindow().setNavigationBarColor(BG);showHome();handleShare(getIntent());}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleShare(i);}
    private void handleShare(Intent i){if(i!=null&&Intent.ACTION_SEND.equals(i.getAction())){CharSequence s=i.getStringExtra(Intent.EXTRA_TEXT);if(s!=null&&!s.toString().trim().isEmpty())showDownloadTool(s.toString());}}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.create("sans-serif",Typeface.NORMAL));t.setIncludeFontPadding(false);return t;}
    private TextView bold(String s,float z){TextView t=text(s,z,TEXT);t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private GradientDrawable box(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp((int)r));g.setStroke(dp(1),Color.rgb(45,55,80));return g;}
    private GradientDrawable gradient(float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{PURPLE,PINK});g.setCornerRadius(dp((int)r));return g;}
    private LinearLayout card(float r){LinearLayout c=col();c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(box(CARD,r));return c;}
    private Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    private TextView icon(String s,float z){TextView t=text(s,z,TEXT);t.setGravity(Gravity.CENTER);return t;}

    private void base(String title,boolean logo,boolean settings){
        LinearLayout root=col();root.setBackgroundColor(BG);root.setFitsSystemWindows(true);
        root.setOnApplyWindowInsetsListener((v,in)->{if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=in.getInsets(WindowInsets.Type.systemBars());v.setPadding(0,x.top,0,x.bottom);}else{v.setPadding(0,in.getSystemWindowInsetTop(),0,in.getSystemWindowInsetBottom());}return in;});
        LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(18),dp(7),dp(18),dp(7));
        if(logo){TextView mark=icon("▷",21);mark.setBackground(gradient(15));bar.addView(mark,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView name=bold("ReelMate",22);name.setPadding(dp(12),0,0,0);bar.addView(name,new LinearLayout.LayoutParams(0,dp(52),1));}
        else {TextView back=icon("‹",34);back.setOnClickListener(v->showHome());bar.addView(back,new LinearLayout.LayoutParams(dp(40),dp(52)));TextView h=bold(title,21);h.setGravity(Gravity.CENTER_VERTICAL);bar.addView(h,new LinearLayout.LayoutParams(0,dp(52),1));}
        if(settings){TextView gear=icon("⚙",23);gear.setBackground(box(CARD2,25));gear.setOnClickListener(v->showSettings());bar.addView(gear,new LinearLayout.LayoutParams(dp(52),dp(52)));}
        root.addView(bar);View line=new View(this);line.setBackgroundColor(Color.rgb(32,40,62));root.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setClipToPadding(true);body=col();body.setPadding(dp(20),dp(13),dp(20),dp(14));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        bottom=nav();root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(72)));setContentView(root);
    }
    private LinearLayout nav(){LinearLayout n=row();n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(3),dp(8),dp(3));n.setBackgroundColor(BAR);String[] a={"⌂","⇩","?","♙"};String[] b={"Home","Downloads","Help","Profile"};for(int i=0;i<4;i++){final int x=i;LinearLayout item=col();item.setGravity(Gravity.CENTER);TextView ic=icon(a[i],23);TextView nm=text(b[i],11,MUTED);nm.setGravity(Gravity.CENTER);item.addView(ic,new LinearLayout.LayoutParams(-1,dp(37)));item.addView(nm,new LinearLayout.LayoutParams(-1,dp(22)));item.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showDownloads();else if(x==2)showHelp();else showProfile();});n.addView(item,new LinearLayout.LayoutParams(0,-1,1));}return n;}
    private void active(int ix){for(int i=0;i<bottom.getChildCount();i++){LinearLayout it=(LinearLayout)bottom.getChildAt(i);TextView ic=(TextView)it.getChildAt(0),nm=(TextView)it.getChildAt(1);if(i==ix){ic.setBackground(gradient(21));ic.setTextColor(TEXT);nm.setTextColor(TEXT);}else{ic.setBackground(null);ic.setTextColor(MUTED);nm.setTextColor(MUTED);}}}

    private void showHome(){base("ReelMate",true,true);body.addView(label("WELCOME BACK"));body.addView(gap(5));body.addView(bold("What are we saving today?",26));TextView sub=text("Save public media you have permission to download.",14,MUTED);sub.setPadding(0,dp(5),0,dp(13));body.addView(sub);
        LinearLayout hero=col();hero.setPadding(dp(17),dp(14),dp(17),dp(14));hero.setBackground(gradient(25));hero.setOnClickListener(v->showDownloadTool(null));LinearLayout hr=row();TextView ic=icon("⇥",27);ic.setBackground(box(Color.argb(45,255,255,255),23));hr.addView(ic,new LinearLayout.LayoutParams(dp(55),dp(55)));LinearLayout hx=col();hx.setPadding(dp(13),0,dp(5),0);hx.addView(bold("Paste a public link",19));hx.addView(text("Instagram · Facebook · X · public pages",13,Color.rgb(244,233,253)));hr.addView(hx,new LinearLayout.LayoutParams(0,-2,1));hr.addView(icon("→",27),new LinearLayout.LayoutParams(dp(32),dp(55)));hero.addView(hr);body.addView(hero);body.addView(gap(11));LinearLayout stats=row();stats.addView(stat("3","Completed"));stats.addView(stat("0","In queue"));stats.addView(stat("68 MB","Used"));body.addView(stats);body.addView(gap(11));
        LinearLayout recent=card(21);LinearLayout rh=row();rh.addView(bold("Recent activity",18),new LinearLayout.LayoutParams(0,dp(27),1));TextView all=text("View all",13,Color.rgb(180,111,255));all.setGravity(Gravity.CENTER_VERTICAL);rh.addView(all);recent.addView(rh);recent.addView(activity("city_night_timelapse.mp4","Instagram · 24.8 MB · Today, 14:20"));recent.addView(activity("morning_desk_setup.mp4","Facebook · 12.1 MB · Yesterday, 09:05"));recent.addView(activity("dusk_mountains_reel.mp4","Instagram · 31.6 MB · 2 Sep, 18:44"));body.addView(recent);active(0);}
    private TextView label(String s){TextView t=text(s,12,MUTED);t.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));t.setLetterSpacing(.08f);return t;}
    private View stat(String v,String s){LinearLayout c=card(18);c.setPadding(dp(11),dp(10),dp(6),dp(8));c.addView(bold(v,21));c.addView(text(s,11,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(72),1);p.setMargins(dp(2),0,dp(2),0);c.setLayoutParams(p);return c;}
    private View activity(String n,String m){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(8),0,0);TextView th=icon("▶",12);th.setBackground(box(Color.rgb(10,17,31),17));r.addView(th,new LinearLayout.LayoutParams(dp(45),dp(45)));LinearLayout x=col();x.setPadding(dp(10),0,0,0);x.addView(bold(n,14));x.addView(text(m,10,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("✓",19,GREEN));return r;}

    private void showDownloadTool(String pre){base("Download Tool",false,false);body.addView(label("PUBLIC LINK"));body.addView(gap(5));body.addView(bold("Save media in a few taps",25));TextView sub=text("Paste a public URL, resolve it, then save the available media.",14,MUTED);sub.setPadding(0,dp(5),0,dp(15));body.addView(sub);LinearLayout c=card(21);c.addView(bold("Media URL",14));urlBox=new EditText(this);urlBox.setTextSize(15);urlBox.setTextColor(TEXT);urlBox.setHintTextColor(MUTED);urlBox.setHint("https://www.instagram.com/reel/...");urlBox.setMinLines(3);urlBox.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);urlBox.setPadding(dp(12),dp(10),dp(12),dp(10));urlBox.setBackground(box(Color.rgb(10,17,32),14));if(pre!=null)urlBox.setText(pre);c.addView(urlBox,new LinearLayout.LayoutParams(-1,dp(96)));TextView paste=text("Paste from clipboard",14,TEXT);paste.setGravity(Gravity.CENTER);paste.setTypeface(Typeface.DEFAULT,Typeface.BOLD);paste.setBackground(box(CARD2,15));paste.setOnClickListener(v->paste());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(44));pp.setMargins(0,dp(10),0,0);c.addView(paste,pp);body.addView(c);body.addView(gap(11));downloadButton=text("Resolve & Download",15,TEXT);downloadButton.setGravity(Gravity.CENTER);downloadButton.setTypeface(Typeface.DEFAULT,Typeface.BOLD);downloadButton.setBackground(gradient(19));downloadButton.setOnClickListener(v->startProcessing());body.addView(downloadButton,new LinearLayout.LayoutParams(-1,dp(54)));toolStatus=text("Supports public links only. Private or login-required content is not bypassed.",12,MUTED);toolStatus.setGravity(Gravity.CENTER);toolStatus.setPadding(dp(5),dp(12),dp(5),0);body.addView(toolStatus);}
    private void paste(){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null&&cm.hasPrimaryClip()){CharSequence s=cm.getPrimaryClip().getItemAt(0).coerceToText(this);if(s!=null)urlBox.setText(s.toString().trim());}}
    private void startProcessing(){String link=urlBox.getText().toString().trim();if(link.isEmpty()){urlBox.setError("Paste a public link first");return;}downloadButton.setEnabled(false);downloadButton.setText("Resolving…");toolStatus.setText("Connecting to ReelMate resolver…");executor.execute(()->{String direct=DownloadResolver.resolveAuthorizedMedia(link);runOnUiThread(()->{if(direct==null){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Could not resolve this public link right now.");}else enqueueDownload(direct);});});}
    private void enqueueDownload(String u){try{DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);DownloadManager.Request r=new DownloadManager.Request(Uri.parse(u));r.setTitle("ReelMate download");r.setDescription("Saved by ReelMate");r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,"ReelMate_"+System.currentTimeMillis()+".mp4");dm.enqueue(r);downloadButton.setEnabled(true);downloadButton.setText("Download started ✓");toolStatus.setText("Saved to Downloads/ReelMate when complete.");}catch(Exception e){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Download could not be started.");}}

    private void showDownloads(){base("Downloads",false,false);TextView search=text("⌕   Search your files",15,MUTED);search.setGravity(Gravity.CENTER_VERTICAL);search.setPadding(dp(15),0,0,0);search.setBackground(box(CARD2,26));body.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));body.addView(gap(13));body.addView(bold("3 FILES · 68.5 MB",13));body.addView(gap(9));body.addView(file("city_night_timelapse.mp4","Instagram · 1080p · 24.8 MB","Today, 14:20"));body.addView(gap(8));body.addView(file("morning_desk_setup.mp4","Facebook · 720p · 12.1 MB","Yesterday, 09:05"));body.addView(gap(8));body.addView(file("dusk_mountains_reel.mp4","Instagram · 1080p · 31.6 MB","2 Sep, 18:44"));active(1);}
    private View file(String n,String m,String d){LinearLayout c=card(21);LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);TextView th=icon("▶",19);th.setBackground(box(Color.rgb(7,12,23),19));r.addView(th,new LinearLayout.LayoutParams(dp(76),dp(76)));LinearLayout x=col();x.setPadding(dp(11),0,0,0);x.addView(bold(n,14));x.addView(text(m,11,MUTED));x.addView(text(d,11,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);LinearLayout ac=row();TextView sh=text("♧  Share",13,TEXT);sh.setGravity(Gravity.CENTER);sh.setTypeface(Typeface.DEFAULT,Typeface.BOLD);sh.setBackground(box(CARD2,23));TextView de=text("♧  Delete",13,Color.rgb(255,103,123));de.setGravity(Gravity.CENTER);de.setTypeface(Typeface.DEFAULT,Typeface.BOLD);de.setBackground(box(Color.rgb(44,27,40),23));ac.addView(sh,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(42),1);q.setMargins(dp(8),0,0,0);ac.addView(de,q);c.addView(ac);return c;}

    private void showHelp(){base("Help & guide",false,false);LinearLayout how=card(21);how.addView(bold("How it works",20));how.addView(step("1","Copy a public link","Open the post, tap Share and choose Copy link."));how.addView(step("2","Paste it in ReelMate","Tap Paste a public link on the home screen."));how.addView(step("3","Pick quality and save","Choose the available media, then download to your library."));body.addView(how);body.addView(gap(11));LinearLayout note=card(20);note.addView(text("♢   ReelMate only works with content that is already public. Please respect creators' rights and local copyright rules when saving media.",13,MUTED));body.addView(note);body.addView(gap(11));faq("Which links are supported?");faq("Where are my files saved?");faq("Why did a public link fail?");active(2);}
    private View step(String n,String t,String d){LinearLayout r=row();r.setPadding(0,dp(14),0,0);TextView num=icon(n,15);num.setBackground(box(Color.rgb(29,37,61),22));num.setTextColor(Color.rgb(177,105,255));r.addView(num,new LinearLayout.LayoutParams(dp(45),dp(45)));LinearLayout x=col();x.setPadding(dp(12),0,0,0);x.addView(bold(n+". "+t,14));x.addView(text(d,12,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private void faq(String q){LinearLayout f=card(17);LinearLayout r=row();r.addView(bold(q,14),new LinearLayout.LayoutParams(0,dp(34),1));r.addView(text("⌄",19,MUTED));f.addView(r);f.setOnClickListener(v->Toast.makeText(this,"ReelMate works with permitted public links. Some sources may require login or may not expose accessible media.",Toast.LENGTH_LONG).show());body.addView(f);body.addView(gap(7));}

    private void showProfile(){base("Profile",false,true);LinearLayout p=card(23);p.setGravity(Gravity.CENTER_HORIZONTAL);TextView av=icon("MR",25);av.setBackground(gradient(65));p.addView(av,new LinearLayout.LayoutParams(dp(128),dp(128)));p.addView(gap(11));p.addView(bold("Malaram",24));TextView role=text("Creator & designer of ReelMate",14,MUTED);role.setGravity(Gravity.CENTER);p.addView(role);p.addView(gap(10));TextView tag=text("Indie developer · India",12,Color.rgb(215,185,255));tag.setGravity(Gravity.CENTER);tag.setBackground(box(Color.rgb(43,29,69),23));p.addView(tag,new LinearLayout.LayoutParams(dp(175),dp(40)));body.addView(p);body.addView(gap(20));body.addView(label("GET IN TOUCH"));body.addView(gap(8));contact("◎","Instagram","@malaramofficial",v->open("https://instagram.com/malaramofficial"));contact("✉","Email","malar amofficial@gmail.com".replace(" ",""),v->open("mailto:malar amofficial@gmail.com".replace(" ","")));contact("◯","WhatsApp","+91 8302776659",v->open("https://wa.me/918302776659"));active(3);}
    private void contact(String i,String t,String v,View.OnClickListener l){LinearLayout c=card(20);c.setGravity(Gravity.CENTER_VERTICAL);LinearLayout r=row();TextView ic=icon(i,23);ic.setTextColor(Color.rgb(173,103,255));ic.setBackground(box(Color.rgb(26,36,58),23));r.addView(ic,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout x=col();x.setPadding(dp(12),0,0,0);x.addView(text(t,12,MUTED));x.addView(bold(v,15));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("›",28,MUTED));c.addView(r);c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(76));p.setMargins(0,0,0,dp(8));body.addView(c,p);}
    private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}}
    private void showSettings(){base("Settings",false,false);setting("Appearance","Dark theme");setting("Download quality","1080p when available");setting("Storage","Downloads / ReelMate");setting("Notifications","Download completion alerts");setting("About ReelMate","Version 1.0");}
    private void setting(String a,String b){LinearLayout c=card(18);LinearLayout r=row();r.addView(bold(a,15),new LinearLayout.LayoutParams(0,-2,1));r.addView(text("›",26,MUTED));c.addView(r);c.addView(text(b,11,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(70));p.setMargins(0,0,0,dp(8));body.addView(c,p);}
    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
