package com.malaram.reelsdownloader;

import android.app.Activity;
import android.app.DownloadManager;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(7,13,28), BAR=Color.rgb(12,17,37), CARD=Color.rgb(23,31,53), CARD2=Color.rgb(29,39,64);
    private static final int TEXT=Color.rgb(248,248,252), MUTED=Color.rgb(158,164,185), PURPLE=Color.rgb(145,78,255), PINK=Color.rgb(201,91,225), GREEN=Color.rgb(54,211,153);
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private LinearLayout body,bottom;
    private EditText urlBox; private TextView toolStatus,downloadButton;

    @Override public void onCreate(Bundle state){super.onCreate(state); getWindow().setStatusBarColor(BAR);getWindow().setNavigationBarColor(BG);showHome();handleShare(getIntent());}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);handleShare(intent);}
    private void handleShare(Intent i){if(i!=null&&Intent.ACTION_SEND.equals(i.getAction())){CharSequence s=i.getStringExtra(Intent.EXTRA_TEXT);if(s!=null&&s.length()>0)showDownloadTool(s.toString());}}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.create("sans",Typeface.NORMAL));return t;}
    private TextView bold(String s,float z){TextView t=text(s,z,TEXT);t.setTypeface(Typeface.create("sans",Typeface.BOLD));return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private GradientDrawable solid(int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp((int)r));g.setStroke(dp(1),Color.rgb(45,55,80));return g;}
    private GradientDrawable grad(float r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{PURPLE,PINK});g.setCornerRadius(dp((int)r));return g;}
    private LinearLayout card(float r){LinearLayout c=col();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(solid(CARD,r));return c;}
    private Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    private TextView label(String s){TextView t=text(s,13,MUTED);t.setTypeface(Typeface.create("sans",Typeface.BOLD));t.setLetterSpacing(.08f);return t;}
    private TextView pill(String s,boolean active){TextView t=text(s,11,active?TEXT:MUTED);t.setGravity(Gravity.CENTER);t.setTypeface(Typeface.create("sans",active?Typeface.BOLD:Typeface.NORMAL));if(active)t.setBackground(grad(22));return t;}
    private TextView icon(String s,float z){TextView t=text(s,z,TEXT);t.setGravity(Gravity.CENTER);return t;}

    private void base(String title,boolean logo,boolean settings){
        LinearLayout root=col();root.setBackgroundColor(BG);
        LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(20),dp(12),dp(20),dp(12));
        if(logo){TextView mark=icon("▷",22);mark.setBackground(grad(16));bar.addView(mark,new LinearLayout.LayoutParams(dp(54),dp(54)));TextView name=bold("ReelMate",23);name.setPadding(dp(14),0,0,0);bar.addView(name,new LinearLayout.LayoutParams(0,dp(54),1));}
        else {TextView back=icon("‹",38);back.setOnClickListener(v->showHome());bar.addView(back,new LinearLayout.LayoutParams(dp(42),dp(54)));TextView h=bold(title,22);h.setGravity(Gravity.CENTER_VERTICAL);bar.addView(h,new LinearLayout.LayoutParams(0,dp(54),1));}
        if(settings){TextView gear=icon("⚙",24);gear.setBackground(solid(CARD2,24));gear.setOnClickListener(v->showSettings());bar.addView(gear,new LinearLayout.LayoutParams(dp(54),dp(54)));}
        root.addView(bar);View line=new View(this);line.setBackgroundColor(Color.rgb(32,40,62));root.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);body=col();body.setPadding(dp(22),dp(20),dp(22),dp(110));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        bottom=nav();root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(86)));setContentView(root);
    }
    private LinearLayout nav(){LinearLayout n=row();n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(5),dp(8),dp(6));n.setBackgroundColor(BAR);String[] a={"⌂","⇩","?","♙"};String[] b={"Home","Downloads","Help","Profile"};for(int i=0;i<4;i++){final int x=i;LinearLayout item=col();item.setGravity(Gravity.CENTER);TextView ic=icon(a[i],25);TextView nm=text(b[i],11,MUTED);nm.setGravity(Gravity.CENTER);item.addView(ic,new LinearLayout.LayoutParams(-1,dp(40)));item.addView(nm,new LinearLayout.LayoutParams(-1,dp(24)));item.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showDownloads();else if(x==2)showHelp();else showProfile();});n.addView(item,new LinearLayout.LayoutParams(0,-1,1));}return n;}
    private void active(int ix){if(bottom==null)return;for(int i=0;i<bottom.getChildCount();i++){LinearLayout it=(LinearLayout)bottom.getChildAt(i);TextView ic=(TextView)it.getChildAt(0);TextView nm=(TextView)it.getChildAt(1);if(i==ix){ic.setBackground(grad(22));ic.setTextColor(TEXT);ic.setTypeface(Typeface.create("sans",Typeface.BOLD));}else{ic.setBackground(null);ic.setTextColor(MUTED);nm.setTextColor(MUTED);}}}

    private void showHome(){
        base("ReelMate",true,true);
        body.addView(label("WELCOME BACK"));body.addView(gap(7));body.addView(bold("What are we saving today?",29));
        TextView sub=text("Save public media you have permission to download.",15,MUTED);sub.setPadding(0,dp(7),0,dp(19));body.addView(sub);
        LinearLayout hero=col();hero.setPadding(dp(20),dp(20),dp(20),dp(20));hero.setBackground(grad(26));hero.setOnClickListener(v->showDownloadTool(null));
        LinearLayout hr=row();TextView ic=icon("⇥",30);ic.setBackground(solid(Color.argb(45,255,255,255),24));hr.addView(ic,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout hx=col();hx.setPadding(dp(15),0,0,0);hx.addView(bold("Paste a public link",22));hx.addView(text("Instagram · Facebook · X · public pages",14,Color.rgb(244,233,253)));hr.addView(hx,new LinearLayout.LayoutParams(0,-2,1));hr.addView(icon("→",28),new LinearLayout.LayoutParams(dp(35),dp(58)));hero.addView(hr);body.addView(hero);
        body.addView(gap(17));LinearLayout stats=row();stats.addView(stat("3","Completed"));stats.addView(stat("0","In queue"));stats.addView(stat("68 MB","Used"));body.addView(stats);body.addView(gap(17));
        LinearLayout recent=card(23);LinearLayout rh=row();rh.addView(bold("Recent activity",19),new LinearLayout.LayoutParams(0,dp(30),1));TextView all=text("View all",14,Color.rgb(180,111,255));all.setGravity(Gravity.CENTER_VERTICAL);rh.addView(all);recent.addView(rh);recent.addView(activity("city_night_timelapse.mp4","Instagram · 24.8 MB · Today, 14:20"));recent.addView(activity("morning_desk_setup.mp4","Facebook · 12.1 MB · Yesterday, 09:05"));recent.addView(activity("dusk_mountains_reel.mp4","Instagram · 31.6 MB · 2 Sep, 18:44"));body.addView(recent);active(0);
    }
    private View stat(String v,String s){LinearLayout c=card(20);c.setPadding(dp(13),dp(13),dp(8),dp(10));c.addView(bold(v,22));c.addView(text(s,12,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(86),1);p.setMargins(dp(3),0,dp(3),0);c.setLayoutParams(p);return c;}
    private View activity(String name,String meta){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(12),0,0);TextView th=icon("▶",14);th.setBackground(solid(Color.rgb(10,17,31),18));r.addView(th,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout x=col();x.setPadding(dp(12),0,0,0);x.addView(bold(name,15));x.addView(text(meta,11,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("✓",20,GREEN));return r;}

    private void showDownloadTool(String prefill){
        base("Download Tool",false,false);body.addView(label("PUBLIC LINK"));body.addView(gap(7));body.addView(bold("Save media in a few taps",27));TextView sub=text("Paste a public URL, resolve it, then save the available media.",15,MUTED);sub.setPadding(0,dp(7),0,dp(20));body.addView(sub);
        LinearLayout c=card(22);c.addView(bold("Media URL",14));urlBox=new EditText(this);urlBox.setTextSize(16);urlBox.setTextColor(TEXT);urlBox.setHintTextColor(MUTED);urlBox.setHint("https://www.instagram.com/reel/...");urlBox.setSingleLine(false);urlBox.setMinLines(3);urlBox.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);urlBox.setPadding(dp(14),dp(12),dp(14),dp(12));urlBox.setBackground(solid(Color.rgb(10,17,32),15));if(prefill!=null)urlBox.setText(prefill);c.addView(urlBox,new LinearLayout.LayoutParams(-1,dp(105)));TextView paste=text("Paste from clipboard",14,TEXT);paste.setGravity(Gravity.CENTER);paste.setTypeface(Typeface.DEFAULT,Typeface.BOLD);paste.setBackground(solid(CARD2,16));paste.setOnClickListener(v->paste());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.setMargins(0,dp(12),0,0);c.addView(paste,pp);body.addView(c);body.addView(gap(14));downloadButton=text("Resolve & Download",16,TEXT);downloadButton.setGravity(Gravity.CENTER);downloadButton.setTypeface(Typeface.DEFAULT,Typeface.BOLD);downloadButton.setBackground(grad(20));downloadButton.setOnClickListener(v->startProcessing());body.addView(downloadButton,new LinearLayout.LayoutParams(-1,dp(58)));toolStatus=text("Supports public links only. Private or login-required content is not bypassed.",13,MUTED);toolStatus.setGravity(Gravity.CENTER);toolStatus.setPadding(dp(5),dp(14),dp(5),0);body.addView(toolStatus);
    }
    private void paste(){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null&&cm.hasPrimaryClip()){CharSequence s=cm.getPrimaryClip().getItemAt(0).coerceToText(this);if(s!=null)urlBox.setText(s.toString().trim());}}
    private void startProcessing(){String link=urlBox==null?"":urlBox.getText().toString().trim();if(link.length()==0){urlBox.setError("Paste a public link first");return;}downloadButton.setEnabled(false);downloadButton.setText("Resolving…");toolStatus.setText("Connecting to ReelMate resolver…");executor.execute(()->{String direct=DownloadResolver.resolveAuthorizedMedia(link);runOnUiThread(()->{if(direct==null){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Could not resolve this public link right now.");}else enqueueDownload(direct);});});}
    private void enqueueDownload(String url){try{DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);DownloadManager.Request r=new DownloadManager.Request(Uri.parse(url));r.setTitle("ReelMate download");r.setDescription("Saved by ReelMate");r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,"ReelMate_"+System.currentTimeMillis()+".mp4");dm.enqueue(r);downloadButton.setEnabled(true);downloadButton.setText("Download started ✓");toolStatus.setText("Saved to Downloads/ReelMate when complete.");}catch(Exception e){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Download could not be started.");}}

    private void showDownloads(){base("Downloads",false,false);TextView search=text("⌕   Search your files",16,MUTED);search.setGravity(Gravity.CENTER_VERTICAL);search.setPadding(dp(17),0,0,0);search.setBackground(solid(CARD2,28));body.addView(search,new LinearLayout.LayoutParams(-1,dp(56)));body.addView(gap(17));LinearLayout sm=row();sm.addView(bold("3 FILES · 68.5 MB",14),new LinearLayout.LayoutParams(0,-2,1));body.addView(sm);body.addView(gap(12));body.addView(file("city_night_timelapse.mp4","Instagram · 1080p · 24.8 MB","Today, 14:20","0:38"));body.addView(gap(10));body.addView(file("morning_desk_setup.mp4","Facebook · 720p · 12.1 MB","Yesterday, 09:05","0:21"));body.addView(gap(10));body.addView(file("dusk_mountains_reel.mp4","Instagram · 1080p · 31.6 MB","2 Sep, 18:44","0:52"));active(1);}
    private View file(String name,String meta,String date,String dur){LinearLayout c=card(23);LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);TextView th=icon("▶",22);th.setBackground(solid(Color.rgb(7,12,23),20));r.addView(th,new LinearLayout.LayoutParams(dp(82),dp(82)));LinearLayout x=col();x.setPadding(dp(13),0,0,0);x.addView(bold(name,15));x.addView(text(meta,12,MUTED));x.addView(text(date,12,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);LinearLayout ac=row();TextView sh=text("♧  Share",14,TEXT);sh.setGravity(Gravity.CENTER);sh.setTypeface(Typeface.DEFAULT,Typeface.BOLD);sh.setBackground(solid(CARD2,25));TextView de=text("♧  Delete",14,Color.rgb(255,103,123));de.setGravity(Gravity.CENTER);de.setTypeface(Typeface.DEFAULT,Typeface.BOLD);de.setBackground(solid(Color.rgb(44,27,40),25));ac.addView(sh,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(46),1);q.setMargins(dp(8),0,0,0);ac.addView(de,q);c.addView(ac);return c;}

    private void showHelp(){base("Help & guide",false,false);LinearLayout how=card(23);how.addView(bold("How it works",21));how.addView(step("1","Copy a public link","Open the post, tap Share and choose Copy link."));how.addView(step("2","Paste it in ReelMate","Tap Paste a public link on the home screen."));how.addView(step("3","Pick quality and save","Choose the available media, then download to your library."));body.addView(how);body.addView(gap(14));LinearLayout note=card(22);note.addView(text("♢   ReelMate only works with content that is already public. Please respect creators' rights and local copyright rules when saving media.",14,MUTED));body.addView(note);body.addView(gap(14));faq("Which links are supported?");faq("Where are my files saved?");faq("Why did a public link fail?");active(2);}
    private View step(String n,String title,String desc){LinearLayout r=row();r.setPadding(0,dp(18),0,0);TextView num=icon(n,16);num.setBackground(solid(Color.rgb(29,37,61),24));num.setTextColor(Color.rgb(177,105,255));r.addView(num,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout x=col();x.setPadding(dp(14),0,0,0);x.addView(bold(n+". "+title,15));x.addView(text(desc,13,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private void faq(String q){LinearLayout f=card(18);LinearLayout r=row();r.addView(bold(q,15),new LinearLayout.LayoutParams(0,dp(38),1));r.addView(text("⌄",20,MUTED));f.addView(r);f.setOnClickListener(v->Toast.makeText(this,"ReelMate works with permitted public links. Some links may fail when the source requires login or does not expose accessible media.",Toast.LENGTH_LONG).show());body.addView(f);body.addView(gap(9));}

    private void showProfile(){base("Profile",false,true);LinearLayout p=card(24);p.setGravity(Gravity.CENTER_HORIZONTAL);TextView av=icon("MR",27);av.setBackground(grad(70));p.addView(av,new LinearLayout.LayoutParams(dp(150),dp(150)));p.addView(gap(14));p.addView(bold("Malaram",26));TextView role=text("Creator & designer of ReelMate",15,MUTED);role.setGravity(Gravity.CENTER);p.addView(role);p.addView(gap(13));TextView tag=text("Indie developer · India",13,Color.rgb(215,185,255));tag.setGravity(Gravity.CENTER);tag.setBackground(solid(Color.rgb(43,29,69),25));p.addView(tag,new LinearLayout.LayoutParams(dp(180),dp(44)));body.addView(p);body.addView(gap(27));body.addView(label("GET IN TOUCH"));body.addView(gap(10));contact("◎","Instagram","@malaramofficial",v->open("https://instagram.com/malaramofficial"));contact("✉","Email","mal aramofficial@gmail.com".replace(" ",""),v->open("mailto:mal aramofficial@gmail.com".replace(" ","")));contact("◯","WhatsApp","+91 8302776659",v->open("https://wa.me/918302776659"));active(3);}
    private void contact(String ic,String title,String value,View.OnClickListener click){LinearLayout c=card(22);c.setGravity(Gravity.CENTER_VERTICAL);LinearLayout r=row();TextView i=icon(ic,25);i.setTextColor(Color.rgb(173,103,255));i.setBackground(solid(Color.rgb(26,36,58),25));r.addView(i,new LinearLayout.LayoutParams(dp(56),dp(56)));LinearLayout x=col();x.setPadding(dp(14),0,0,0);x.addView(text(title,13,MUTED));x.addView(bold(value,16));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(text("›",30,MUTED));c.addView(r);c.setOnClickListener(click);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(84));p.setMargins(0,0,0,dp(10));body.addView(c,p);}
    private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}}

    private void showSettings(){base("Settings",false,false);setting("Appearance","Dark theme",v->{});setting("Download quality","1080p when available",v->{});setting("Storage","Downloads / ReelMate",v->{});setting("Notifications","Download completion alerts",v->{});setting("About ReelMate","Version 1.0",v->{});}
    private void setting(String a,String b,View.OnClickListener l){LinearLayout c=card(20);LinearLayout r=row();r.addView(bold(a,16),new LinearLayout.LayoutParams(0,-2,1));r.addView(text("›",28,MUTED));c.addView(r);c.addView(text(b,12,MUTED));c.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(76));p.setMargins(0,0,0,dp(10));body.addView(c,p);}

    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
