package com.malaram.reelsdownloader;

import android.app.*;
import android.app.DownloadManager;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private static final int BG=Color.rgb(9,15,30), SURFACE=Color.rgb(19,29,48), SURFACE2=Color.rgb(26,38,61);
    private static final int TEXT=Color.rgb(245,247,252), MUTED=Color.rgb(158,171,195), ACCENT=Color.rgb(142,76,255), ACCENT2=Color.rgb(203,86,224), GREEN=Color.rgb(55,211,153);
    private final ExecutorService executor=Executors.newSingleThreadExecutor();
    private LinearLayout body, bottom;
    private EditText urlBox; private TextView toolStatus; private Button downloadButton;

    @Override public void onCreate(Bundle state){ super.onCreate(state); getWindow().setStatusBarColor(BG); getWindow().setNavigationBarColor(BG); showHome(); handleShare(getIntent()); }
    @Override protected void onNewIntent(Intent intent){ super.onNewIntent(intent); setIntent(intent); handleShare(intent); }
    private void handleShare(Intent i){ if(i!=null && Intent.ACTION_SEND.equals(i.getAction())){ CharSequence s=i.getStringExtra(Intent.EXTRA_TEXT); if(s!=null && s.length()>0) showDownloadTool(s.toString()); } }

    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private TextView tv(String s,float size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");return t;}
    private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}
    private GradientDrawable bg(int color,float radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp((int)radius));return g;}
    private GradientDrawable gradient(float radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{ACCENT,ACCENT2});g.setCornerRadius(dp((int)radius));return g;}
    private TextView label(String s){TextView t=tv(s,13,MUTED);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setLetterSpacing(.08f);return t;}
    private TextView heading(String s,float size){TextView t=tv(s,size,TEXT);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private Space gap(int h){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return s;}
    private LinearLayout card(int radius){LinearLayout c=col();c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bg(SURFACE,radius));return c;}
    private Button action(String s){Button b=new Button(this);b.setText(s);b.setTextSize(15);b.setTextColor(TEXT);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(gradient(18));return b;}

    private void base(String title, boolean back, boolean settings){
        LinearLayout root=col();root.setBackgroundColor(BG);
        LinearLayout bar=row();bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(18),dp(12),dp(18),dp(12));
        if(back){TextView b=tv("‹",38,TEXT);b.setGravity(Gravity.CENTER);b.setOnClickListener(v->showHome());bar.addView(b,new LinearLayout.LayoutParams(dp(42),dp(48)));}
        else {TextView mark=tv("RM",17,TEXT);mark.setGravity(Gravity.CENTER);mark.setTypeface(Typeface.DEFAULT,Typeface.BOLD);mark.setBackground(gradient(16));bar.addView(mark,new LinearLayout.LayoutParams(dp(50),dp(50)));}
        TextView h=heading(title,22);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(12),0,0,0);bar.addView(h,new LinearLayout.LayoutParams(0,dp(50),1));
        if(settings){TextView s=tv("⚙",24,TEXT);s.setGravity(Gravity.CENTER);s.setBackground(bg(SURFACE2,18));s.setOnClickListener(v->showSettings());bar.addView(s,new LinearLayout.LayoutParams(dp(50),dp(50)));}
        root.addView(bar); View line=new View(this);line.setBackgroundColor(Color.rgb(31,44,67));root.addView(line,new LinearLayout.LayoutParams(-1,1));
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=col();body.setPadding(dp(18),dp(18),dp(18),dp(105));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        bottom=nav();root.addView(bottom,new LinearLayout.LayoutParams(-1,dp(78)));setContentView(root);
    }

    private LinearLayout nav(){LinearLayout n=row();n.setGravity(Gravity.CENTER);n.setPadding(dp(8),dp(6),dp(8),dp(8));n.setBackgroundColor(Color.rgb(12,20,36));String[] names={"Home","Downloads","Help","Profile"};String[] icons={"⌂","↓","?","○"};for(int i=0;i<4;i++){final int x=i;LinearLayout item=col();item.setGravity(Gravity.CENTER);TextView ic=tv(icons[i],23,MUTED);ic.setGravity(Gravity.CENTER);TextView nm=tv(names[i],11,MUTED);nm.setGravity(Gravity.CENTER);item.addView(ic,new LinearLayout.LayoutParams(-1,dp(30)));item.addView(nm);item.setOnClickListener(v->{if(x==0)showHome();else if(x==1)showDownloads();else if(x==2)showHelp();else showProfile();});n.addView(item,new LinearLayout.LayoutParams(0,-1,1));}return n;}
    private void activeNav(int index){ if(bottom==null)return; for(int i=0;i<bottom.getChildCount();i++){LinearLayout item=(LinearLayout)bottom.getChildAt(i);TextView ic=(TextView)item.getChildAt(0), nm=(TextView)item.getChildAt(1);boolean a=i==index;ic.setTextColor(a?TEXT:MUTED);nm.setTextColor(a?TEXT:MUTED);if(a){ic.setBackground(gradient(15));ic.setPadding(dp(18),0,dp(18),0);}else ic.setBackground(null);} }

    private void showHome(){
        base("ReelMate",false,true);
        TextView over=label("WELCOME BACK");body.addView(over);body.addView(gap(8));body.addView(heading("What are we saving today?",30));TextView sub=tv("Save public media you have permission to download.",15,MUTED);sub.setPadding(0,dp(8),0,dp(20));body.addView(sub);
        LinearLayout hero=col();hero.setPadding(dp(20),dp(20),dp(20),dp(20));hero.setBackground(gradient(24));hero.setOnClickListener(v->showDownloadTool(null));
        TextView small=tv("QUICK DOWNLOAD",12,Color.WHITE);small.setTypeface(Typeface.DEFAULT,Typeface.BOLD);small.setLetterSpacing(.08f);hero.addView(small);hero.addView(gap(8));hero.addView(heading("Paste a public link",23));TextView hs=tv("Instagram · Facebook · X · public pages",14,Color.rgb(240,230,255));hs.setPadding(0,dp(6),0,dp(18));hero.addView(hs);Button hb=action("Open Download Tool   →");hero.addView(hb,new LinearLayout.LayoutParams(-1,dp(52)));body.addView(hero);
        body.addView(gap(18));LinearLayout stats=row();stats.addView(stat("3","Completed"));stats.addView(stat("0","In queue"));stats.addView(stat("68 MB","Used"));body.addView(stats);body.addView(gap(18));
        LinearLayout recent=card(22);LinearLayout rh=row();rh.addView(heading("Recent activity",19),new LinearLayout.LayoutParams(0,dp(30),1));TextView va=tv("View all",14,Color.rgb(177,112,255));rh.addView(va);recent.addView(rh);recent.addView(activity("city_night_timelapse.mp4","Instagram · 1080p · 24.8 MB"));recent.addView(activity("morning_desk_setup.mp4","Facebook · 720p · 12.1 MB"));recent.addView(activity("dusk_mountains_reel.mp4","Instagram · 1080p · 31.6 MB"));body.addView(recent);activeNav(0);
    }
    private View stat(String value,String text){LinearLayout c=card(18);c.setPadding(dp(14),dp(12),dp(10),dp(12));c.addView(heading(value,21));c.addView(tv(text,12,MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(78),1);p.setMargins(dp(3),0,dp(3),0);c.setLayoutParams(p);return c;}
    private View activity(String name,String meta){LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(13),0,0);TextView icon=tv("▶",15,TEXT);icon.setGravity(Gravity.CENTER);icon.setBackground(bg(Color.rgb(12,19,33),16));r.addView(icon,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout x=col();x.setPadding(dp(12),0,0,0);TextView n=heading(name,15);TextView m=tv(meta,12,MUTED);x.addView(n);x.addView(m);r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(tv("✓",20,GREEN));return r;}

    private void showDownloadTool(String prefill){
        base("Download Tool",true,false);TextView over=label("PUBLIC LINK");body.addView(over);body.addView(gap(7));body.addView(heading("Save media in a few taps",27));TextView sub=tv("Paste a public URL, resolve it, then save the available media.",15,MUTED);sub.setPadding(0,dp(7),0,dp(20));body.addView(sub);
        LinearLayout input=card(20);TextView il=heading("Media URL",14);input.addView(il);urlBox=new EditText(this);urlBox.setSingleLine(false);urlBox.setMinLines(3);urlBox.setTextSize(16);urlBox.setTextColor(TEXT);urlBox.setHintTextColor(MUTED);urlBox.setHint("https://www.instagram.com/reel/...");urlBox.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);urlBox.setPadding(dp(12),dp(12),dp(12),dp(12));urlBox.setBackground(bg(Color.rgb(11,19,34),14));if(prefill!=null)urlBox.setText(prefill);input.addView(urlBox,new LinearLayout.LayoutParams(-1,-2));Button pb=action("Paste from clipboard");pb.setOnClickListener(v->paste());LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.setMargins(0,dp(12),0,0);input.addView(pb,pp);body.addView(input);
        body.addView(gap(14));downloadButton=action("Resolve & Download");downloadButton.setOnClickListener(v->startProcessing());body.addView(downloadButton,new LinearLayout.LayoutParams(-1,dp(56)));toolStatus=tv("Supports public links only. Private or login-required content is not bypassed.",13,MUTED);toolStatus.setGravity(Gravity.CENTER);toolStatus.setPadding(dp(4),dp(14),dp(4),0);body.addView(toolStatus);
    }
    private void paste(){android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(c!=null&&c.hasPrimaryClip()){CharSequence s=c.getPrimaryClip().getItemAt(0).coerceToText(this);if(s!=null){urlBox.setText(s.toString().trim());toolStatus.setText("Link pasted. Ready to resolve.");}}else toolStatus.setText("No text link found in clipboard.");}
    private void startProcessing(){String link=urlBox==null?"":urlBox.getText().toString().trim();if(link.length()==0){urlBox.setError("Paste a public link first");return;}downloadButton.setEnabled(false);downloadButton.setText("Resolving…");toolStatus.setText("Connecting to ReelMate resolver…");executor.execute(()->{String direct=DownloadResolver.resolveAuthorizedMedia(link);runOnUiThread(()->{if(direct==null){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Could not resolve this public link right now.");}else enqueueDownload(direct);});});}
    private void enqueueDownload(String url){try{DownloadManager dm=(DownloadManager)getSystemService(DOWNLOAD_SERVICE);DownloadManager.Request r=new DownloadManager.Request(Uri.parse(url));r.setTitle("ReelMate download");r.setDescription("Saved by ReelMate");r.setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED);r.setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,"ReelMate_"+System.currentTimeMillis()+".mp4");dm.enqueue(r);downloadButton.setEnabled(true);downloadButton.setText("Download started ✓");toolStatus.setText("Saved to Downloads/ReelMate when complete.");}catch(Exception e){downloadButton.setEnabled(true);downloadButton.setText("Resolve & Download");toolStatus.setText("Download could not be started.");}}

    private void showDownloads(){base("Downloads",false,false);TextView s=tv("Search your files",16,MUTED);s.setPadding(dp(18),0,0,0);s.setGravity(Gravity.CENTER_VERTICAL);s.setBackground(bg(SURFACE2,18));body.addView(s,new LinearLayout.LayoutParams(-1,dp(54)));body.addView(gap(16));LinearLayout summary=row();summary.addView(heading("3 files",19),new LinearLayout.LayoutParams(0,-2,1));summary.addView(tv("68.5 MB used",13,MUTED));body.addView(summary);body.addView(gap(12));body.addView(file("city_night_timelapse.mp4","Instagram · 1080p · 24.8 MB","0:38"));body.addView(gap(10));body.addView(file("morning_desk_setup.mp4","Facebook · 720p · 12.1 MB","0:21"));body.addView(gap(10));body.addView(file("dusk_mountains_reel.mp4","Instagram · 1080p · 31.6 MB","0:52"));activeNav(1);}
    private View file(String name,String meta,String dur){LinearLayout c=card(20);LinearLayout r=row();r.setGravity(Gravity.CENTER_VERTICAL);TextView thumb=tv("▶",22,TEXT);thumb.setGravity(Gravity.CENTER);thumb.setBackground(bg(Color.rgb(7,12,23),17));r.addView(thumb,new LinearLayout.LayoutParams(dp(82),dp(82)));LinearLayout x=col();x.setPadding(dp(12),0,dp(4),0);x.addView(heading(name,15));x.addView(tv(meta,12,MUTED));x.addView(tv(dur,11,Color.rgb(196,181,224)));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));c.addView(r);LinearLayout actions=row();Button sh=action("Share");sh.setBackground(bg(SURFACE2,14));Button de=action("Delete");de.setTextColor(Color.rgb(255,110,125));de.setBackground(bg(Color.rgb(40,27,38),14));actions.addView(sh,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,dp(42),1);q.setMargins(dp(8),0,0,0);actions.addView(de,q);c.addView(actions);return c;}

    private void showHelp(){base("Help & Guide",false,false);LinearLayout how=card(22);how.addView(heading("How it works",21));how.addView(step("01","Copy a public link","Open the post and use Share → Copy link."));how.addView(step("02","Paste it in ReelMate","Open Download Tool and paste the link."));how.addView(step("03","Resolve and save","ReelMate resolves available public media and starts the download."));body.addView(how);body.addView(gap(14));LinearLayout note=card(20);note.addView(heading("Supported content",17));note.addView(tv("Public media you are permitted to save. Private, deleted or login-required content is not bypassed.",14,MUTED));body.addView(note);body.addView(gap(14));faq("Which links are supported?");faq("Where are my files saved?");faq("Why did a public link fail?");activeNav(2);}
    private View step(String num,String title,String desc){LinearLayout r=row();r.setPadding(0,dp(17),0,0);TextView n=tv(num,12,Color.WHITE);n.setGravity(Gravity.CENTER);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);n.setBackground(gradient(14));r.addView(n,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout x=col();x.setPadding(dp(12),0,0,0);x.addView(heading(title,15));x.addView(tv(desc,13,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));return r;}
    private void faq(String q){LinearLayout f=card(18);LinearLayout r=row();r.addView(heading(q,15),new LinearLayout.LayoutParams(0,-2,1));r.addView(tv("⌄",20,MUTED));f.addView(r);f.setOnClickListener(v->Toast.makeText(this,"ReelMate works with permitted public links. If a link fails, the source may require login or may no longer expose accessible media.",Toast.LENGTH_LONG).show());body.addView(f);body.addView(gap(9));}

    private void showProfile(){base("Profile",false,true);LinearLayout p=card(24);p.setGravity(Gravity.CENTER_HORIZONTAL);TextView avatar=tv("MR",27,TEXT);avatar.setGravity(Gravity.CENTER);avatar.setTypeface(Typeface.DEFAULT,Typeface.BOLD);avatar.setBackground(gradient(48));p.addView(avatar,new LinearLayout.LayoutParams(dp(104),dp(104)));TextView name=heading("Malaram",26);name.setPadding(0,dp(16),0,dp(4));p.addView(name);TextView role=tv("Creator & designer of ReelMate",14,MUTED);p.addView(role);TextView chip=tv("Indie developer · India",13,TEXT);chip.setGravity(Gravity.CENTER);chip.setBackground(bg(Color.rgb(47,34,67),18));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(190),dp(38));cp.setMargins(0,dp(12),0,0);p.addView(chip,cp);body.addView(p);TextView gt=label("GET IN TOUCH");gt.setPadding(dp(4),dp(24),0,dp(10));body.addView(gt);contact("Instagram","@malaramofficial",v->open("https://www.instagram.com/malaramofficial/"));contact("Email","malaramofficial@gmail.com",v->open("mailto:malaramofficial@gmail.com"));contact("WhatsApp","+91 8302776659",v->open("https://wa.me/918302776659"));activeNav(3);}
    private void contact(String title,String value,View.OnClickListener l){LinearLayout c=card(18);LinearLayout r=row();TextView icon=tv(title.equals("Instagram")?"◎":title.equals("Email")?"✉":"◯",23,Color.rgb(173,109,255));icon.setGravity(Gravity.CENTER);icon.setBackground(bg(Color.rgb(28,38,59),15));r.addView(icon,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout x=col();x.setPadding(dp(13),0,0,0);x.addView(tv(title,12,MUTED));x.addView(heading(value,15));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));r.addView(tv("›",28,MUTED));c.addView(r);c.setOnClickListener(l);body.addView(c);body.addView(gap(9));}
    private void open(String u){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception ignored){}}

    private void showSettings(){base("Settings",true,false);body.addView(section("APPEARANCE","Theme","Dark · ReelMate Night",false));body.addView(section("DOWNLOAD","Default quality","Best available",true));body.addView(section("DOWNLOAD","Save location","Downloads / ReelMate",false));body.addView(section("BEHAVIOR","Notifications","Download completion alerts",true));body.addView(section("ABOUT","Version","1.0 · ReelMate",false));LinearLayout clear=card(18);TextView c=heading("Clear recent activity",15);c.setTextColor(Color.rgb(255,110,125));clear.addView(c);clear.setOnClickListener(v->Toast.makeText(this,"Recent activity cleared.",Toast.LENGTH_SHORT).show());body.addView(gap(10));body.addView(clear);}
    private View section(String group,String title,String sub,boolean toggle){LinearLayout wrap=col();wrap.addView(label(group));wrap.addView(gap(7));LinearLayout c=card(18);LinearLayout r=row();LinearLayout x=col();x.addView(heading(title,15));x.addView(tv(sub,12,MUTED));r.addView(x,new LinearLayout.LayoutParams(0,-2,1));if(toggle){Switch sw=new Switch(this);sw.setChecked(true);r.addView(sw);}else r.addView(tv("›",24,MUTED));c.addView(r);wrap.addView(c);wrap.addView(gap(14));return wrap;}

    @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
