package com.malaram.reelsdownloader;
import android.app.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;
public class ProfileActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Ui.NAVY);LinearLayout r=root();TextView back=Ui.text(this,"‹",36,Color.WHITE);back.setOnClickListener(v->finish());r.addView(back);TextView title=Ui.heading(this,"Creator Profile");r.addView(title);TextView sub=Ui.subtitle(this,"The person behind ReelMate");r.addView(sub);Ui.space(r,this,22);
 LinearLayout c=Ui.card(this,Ui.CARD);TextView avatar=Ui.text(this,"M",34,Color.WHITE);avatar.setGravity(Gravity.CENTER);avatar.setTypeface(null,1);avatar.setBackground(Ui.bg(this,Ui.PURPLE,44));c.addView(avatar,new LinearLayout.LayoutParams(Ui.dp(this,88),Ui.dp(this,88)));
 TextView n=Ui.text(this,"Mala Ram",24,Color.WHITE);n.setTypeface(null,1);n.setPadding(0,Ui.dp(this,14),0,0);c.addView(n);c.addView(Ui.subtitle(this,"Creator & Developer"));Ui.space(c,this,14);
 link(c,"Instagram","@malaramofficial","https://www.instagram.com/malaramofficial/");link(c,"Email","malaramofficial@gmail.com","mailto:malaramofficial@gmail.com");link(c,"WhatsApp","+91 8302776659","https://wa.me/918302776659");r.addView(c);setContentView(r);}
 LinearLayout root(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(Ui.dp(this,20),Ui.dp(this,18),Ui.dp(this,20),Ui.dp(this,20));r.setBackgroundColor(Ui.NAVY);return r;}
 void link(LinearLayout c,String a,String b,String u){TextView x=Ui.text(this,a+"\n"+b,15,Color.WHITE);x.setPadding(Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14),Ui.dp(this,14));x.setBackground(Ui.bg(this,Color.rgb(51,65,85),14));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=Ui.dp(this,10);c.addView(x,p);x.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){}});}
}